-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 14:02:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema refugeedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema refugeedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `refugeedb` DEFAULT CHARACTER SET greek ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `MKO_TYPE` INT NOT NULL,
  `TYPE_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`MKO_TYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsibility` (
  `RESPONSIBILITY_ID` INT NOT NULL,
  `TITLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RESPONSIBILITY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_has_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_has_type` (
  `type_MKO_TYPE` INT NOT NULL,
  `type_MKO_TYPE1` INT NOT NULL,
  PRIMARY KEY (`type_MKO_TYPE`, `type_MKO_TYPE1`),
  INDEX `fk_type_has_type_type1_idx` (`type_MKO_TYPE1` ASC) VISIBLE,
  INDEX `fk_type_has_type_type_idx` (`type_MKO_TYPE` ASC) VISIBLE,
  CONSTRAINT `fk_type_has_type_type`
    FOREIGN KEY (`type_MKO_TYPE`)
    REFERENCES `mydb`.`type` (`MKO_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type_has_type_type1`
    FOREIGN KEY (`type_MKO_TYPE1`)
    REFERENCES `mydb`.`type` (`MKO_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `refugeedb` ;

-- -----------------------------------------------------
-- Table `refugeedb`.`government`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`government` (
  `GOV_ID` INT NOT NULL,
  `GOV_NAME` VARCHAR(45) NOT NULL,
  `GOV_RESPONSIBILITY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GOV_ID`),
  UNIQUE INDEX `GOV_ID_UNIQUE` (`GOV_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`accomodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`accomodation` (
  `ACC_ID` INT NOT NULL,
  `ACC_ADRESS` VARCHAR(45) NOT NULL,
  `GOV_ID` INT NOT NULL,
  PRIMARY KEY (`ACC_ID`),
  UNIQUE INDEX `ACC_ID_UNIQUE` (`ACC_ID` ASC) VISIBLE,
  INDEX `GOVERNMENT_idx` (`GOV_ID` ASC) VISIBLE,
  CONSTRAINT `ACCGOV`
    FOREIGN KEY (`GOV_ID`)
    REFERENCES `refugeedb`.`government` (`GOV_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`mko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`mko` (
  `MKO_VAT` VARCHAR(9) NOT NULL,
  `MKO_NAME` VARCHAR(45) NOT NULL,
  `MKO_TYPE` INT NOT NULL,
  PRIMARY KEY (`MKO_VAT`),
  UNIQUE INDEX `MKO_VAT_UNIQUE` (`MKO_VAT` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`supplier` (
  `SUP_VAT` VARCHAR(9) NOT NULL,
  `SUP_NAME` VARCHAR(45) NOT NULL,
  `SUP_ADDRESS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SUP_VAT`),
  UNIQUE INDEX `SUP_VAT_UNIQUE` (`SUP_VAT` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`supply` (
  `SUPPLY_ID` INT NOT NULL,
  `SUPPLY_DATE` DATE NOT NULL,
  `TOTAL_PRICE` DECIMAL(10,0) NOT NULL,
  `QUANTITY` INT NOT NULL,
  `SUP_VAT` VARCHAR(9) NOT NULL,
  `MKO_VAT` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`SUPPLY_ID`),
  UNIQUE INDEX `EX_ID_UNIQUE` (`SUPPLY_ID` ASC) VISIBLE,
  INDEX `SELLER_idx` (`SUP_VAT` ASC) VISIBLE,
  INDEX `BUYER_idx` (`MKO_VAT` ASC) VISIBLE,
  CONSTRAINT `BUYER`
    FOREIGN KEY (`MKO_VAT`)
    REFERENCES `refugeedb`.`mko` (`MKO_VAT`),
  CONSTRAINT `SELLER`
    FOREIGN KEY (`SUP_VAT`)
    REFERENCES `refugeedb`.`supplier` (`SUP_VAT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`allergies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`allergies` (
  `ALL_ID` INT NOT NULL,
  `SUPPLY_ID` INT NOT NULL,
  PRIMARY KEY (`ALL_ID`),
  INDEX `SUPPLY_idx` (`SUPPLY_ID` ASC) VISIBLE,
  CONSTRAINT `SUPPLY`
    FOREIGN KEY (`SUPPLY_ID`)
    REFERENCES `refugeedb`.`supply` (`SUPPLY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`camp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`camp` (
  `ACC_ID` INT NOT NULL,
  `BEDS` INT NOT NULL,
  `ACC_TYPE` VARCHAR(1) NOT NULL,
  `REF_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ACC_ID`),
  CONSTRAINT `ACCOMODATION`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `refugeedb`.`accomodation` (`ACC_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`refugee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`refugee` (
  `REF_ID` INT NOT NULL,
  `REF_NAME` VARCHAR(45) NOT NULL,
  `REF_SURNAME` VARCHAR(45) NOT NULL,
  `REF_GENDER` VARCHAR(1) NOT NULL,
  `REF_AGE` INT NOT NULL,
  `REF_COUNTRY` VARCHAR(3) NOT NULL,
  `REF_ENTRY_DATE` DATE NOT NULL,
  `ACC_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`REF_ID`),
  UNIQUE INDEX `idREFUGEE_UNIQUE` (`REF_ID` ASC) VISIBLE,
  INDEX `REF_COUNTRY_idx` (`REF_COUNTRY` ASC) VISIBLE,
  INDEX `ACC_ID_idx` (`ACC_ID` ASC) VISIBLE,
  CONSTRAINT `ACC_ID`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `refugeedb`.`accomodation` (`ACC_ID`),
  CONSTRAINT `REF_COUNTRY`
    FOREIGN KEY (`REF_COUNTRY`)
    REFERENCES `refugeedb`.`countries` (`C_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`countries` (
  `C_CODE` VARCHAR(3) NOT NULL,
  `C_NAME` VARCHAR(20) NOT NULL,
  `REPRESENTATIVE_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`C_CODE`),
  UNIQUE INDEX `REPRESENTATIVE_ID_UNIQUE` (`REPRESENTATIVE_ID` ASC) VISIBLE,
  INDEX `REF_ID_idx` (`REPRESENTATIVE_ID` ASC) VISIBLE,
  CONSTRAINT `REPRESENTATIVE`
    FOREIGN KEY (`REPRESENTATIVE_ID`)
    REFERENCES `refugeedb`.`refugee` (`REF_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`volunteer` (
  `VOL_ID` VARCHAR(10) NOT NULL,
  `VOL_NAME` VARCHAR(20) NOT NULL,
  `VOL_SURNAME` VARCHAR(20) NOT NULL,
  `VOL_GENDER` VARCHAR(1) NOT NULL,
  `VOL_AGE` INT NOT NULL,
  `VOL_SPECIALTY` VARCHAR(45) NOT NULL,
  `VOL_MKO` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`VOL_ID`),
  UNIQUE INDEX `VOL_ID_UNIQUE` (`VOL_ID` ASC) VISIBLE,
  INDEX `FROM_MKO_idx` (`VOL_MKO` ASC) VISIBLE,
  CONSTRAINT `FROM_MKO`
    FOREIGN KEY (`VOL_MKO`)
    REFERENCES `refugeedb`.`mko` (`MKO_VAT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`doctor` (
  `VOL_ID` VARCHAR(10) NOT NULL,
  `DOC_ID` INT NOT NULL,
  `DOC_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DOC_ID`, `VOL_ID`),
  UNIQUE INDEX `VOL_ID_UNIQUE` (`VOL_ID` ASC) VISIBLE,
  UNIQUE INDEX `DOC_ID_UNIQUE` (`DOC_ID` ASC) VISIBLE,
  CONSTRAINT `VOLUNTEER`
    FOREIGN KEY (`VOL_ID`)
    REFERENCES `refugeedb`.`volunteer` (`VOL_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`family` (
  `FAM_ID` INT NOT NULL,
  `MEMBERS` INT NOT NULL,
  PRIMARY KEY (`FAM_ID`),
  UNIQUE INDEX `FAM_ID_UNIQUE` (`FAM_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`food_clothes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`food_clothes` (
  `BARCODE` VARCHAR(10) NOT NULL,
  `SUPPLY_ID` INT NOT NULL DEFAULT NULL,
  `PRODUCT_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BARCODE`, `SUPPLY_ID`),
  INDEX `FOOD_PROD_idx` (`SUPPLY_ID` ASC) VISIBLE,
  CONSTRAINT `FOOD_PROD`
    FOREIGN KEY (`SUPPLY_ID`)
    REFERENCES `refugeedb`.`supply` (`SUPPLY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`hospital` (
  `HOS_ID` INT NOT NULL,
  `HOS_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `GOV_ID` INT NULL DEFAULT NULL,
  `HOS_ADDRESS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HOS_ID`),
  UNIQUE INDEX `HOS_ID_UNIQUE` (`HOS_ID` ASC) VISIBLE,
  INDEX `GOVERN_idx` (`GOV_ID` ASC) VISIBLE,
  CONSTRAINT `GOVERN`
    FOREIGN KEY (`GOV_ID`)
    REFERENCES `refugeedb`.`government` (`GOV_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`medicine` (
  `MED_ID` INT NOT NULL,
  `SUPPLY_ID` INT NOT NULL,
  `MED_BATCH` VARCHAR(10) NOT NULL,
  `MED_DRUG` VARCHAR(45) NOT NULL,
  `MED_MG` FLOAT NOT NULL,
  `DOC_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`MED_ID`, `SUPPLY_ID`),
  UNIQUE INDEX `MED_ID_UNIQUE` (`SUPPLY_ID` ASC) VISIBLE,
  INDEX `FROM DOCTOR_idx` (`DOC_ID` ASC) VISIBLE,
  CONSTRAINT `DOCTOR_WRITES`
    FOREIGN KEY (`DOC_ID`)
    REFERENCES `refugeedb`.`doctor` (`DOC_ID`),
  CONSTRAINT `SUPLLY_MEDS`
    FOREIGN KEY (`SUPPLY_ID`)
    REFERENCES `refugeedb`.`supply` (`SUPPLY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`hospita diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`hospita diagnosis` (
  `DIAGNOSIS_ID` INT NOT NULL,
  `DIAGNOSIS` VARCHAR(45) NULL DEFAULT NULL,
  `MED_TREATMENT` INT NOT NULL,
  `DATE ENTRY` DATE NOT NULL,
  `DATE EXIT` DATE NULL DEFAULT NULL,
  `HOS_ID` INT NULL DEFAULT NULL,
  `REF_ID` INT NOT NULL,
  `WRITEN_FROM_DOC` INT NULL DEFAULT NULL,
  PRIMARY KEY (`DIAGNOSIS_ID`),
  UNIQUE INDEX `DIAGNOSIS_ID_UNIQUE` (`DIAGNOSIS_ID` ASC) VISIBLE,
  INDEX `HOSPITAL_idx` (`HOS_ID` ASC) VISIBLE,
  INDEX `REFUGEE_idx` (`REF_ID` ASC) VISIBLE,
  INDEX `DOCTOR_idx` (`WRITEN_FROM_DOC` ASC) VISIBLE,
  INDEX `MED_TREAT_idx` (`MED_TREATMENT` ASC) VISIBLE,
  CONSTRAINT `DOCTOR`
    FOREIGN KEY (`WRITEN_FROM_DOC`)
    REFERENCES `refugeedb`.`doctor` (`DOC_ID`),
  CONSTRAINT `HOSPITAL`
    FOREIGN KEY (`HOS_ID`)
    REFERENCES `refugeedb`.`hospital` (`HOS_ID`),
  CONSTRAINT `MED_TREAT`
    FOREIGN KEY (`MED_TREATMENT`)
    REFERENCES `refugeedb`.`medicine` (`MED_ID`),
  CONSTRAINT `REFUGEE`
    FOREIGN KEY (`REF_ID`)
    REFERENCES `refugeedb`.`refugee` (`REF_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`private house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`private house` (
  `ACC_ID` INT NOT NULL,
  `SQUARE_METERS` DECIMAL(10,0) NOT NULL,
  `ROOMS` INT NOT NULL,
  PRIMARY KEY (`ACC_ID`),
  CONSTRAINT `HOUSE ACC`
    FOREIGN KEY (`ACC_ID`)
    REFERENCES `refugeedb`.`accomodation` (`ACC_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`request` (
  `REQ_ID` INT NOT NULL,
  `REQ_DATE` DATE NOT NULL,
  `REQ_DONE` DATE NULL DEFAULT NULL,
  `REQ_DESC` VARCHAR(100) NOT NULL,
  `REQ_RESULT` INT NULL DEFAULT NULL,
  `REF_ID` INT NOT NULL,
  `GOV_ID` INT NOT NULL,
  PRIMARY KEY (`REQ_ID`),
  UNIQUE INDEX `REQ_ID_UNIQUE` (`REQ_ID` ASC) VISIBLE,
  INDEX `REF_ID_idx` (`REF_ID` ASC) VISIBLE,
  INDEX `GOV_ID_idx` (`GOV_ID` ASC) VISIBLE,
  CONSTRAINT `GOV_ID`
    FOREIGN KEY (`GOV_ID`)
    REFERENCES `refugeedb`.`government` (`GOV_ID`),
  CONSTRAINT `REF_ID`
    FOREIGN KEY (`REF_ID`)
    REFERENCES `refugeedb`.`refugee` (`REF_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`school` (
  `SCH_ID` INT NOT NULL,
  `SCH_NAME` VARCHAR(45) NOT NULL,
  `SCH_GRADE` VARCHAR(45) NOT NULL,
  `GOV_ID` INT NOT NULL,
  PRIMARY KEY (`SCH_ID`),
  UNIQUE INDEX `SCH_ID_UNIQUE` (`SCH_ID` ASC) VISIBLE,
  INDEX `GOVERNMENT_idx` (`GOV_ID` ASC) VISIBLE,
  CONSTRAINT `GOVERNMENT`
    FOREIGN KEY (`GOV_ID`)
    REFERENCES `refugeedb`.`government` (`GOV_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`mko_has_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`mko_has_type` (
  `mko_MKO_VAT` VARCHAR(9) NOT NULL,
  `type_MKO_TYPE` INT NOT NULL,
  PRIMARY KEY (`mko_MKO_VAT`, `type_MKO_TYPE`),
  INDEX `fk_mko_has_type_type1_idx` (`type_MKO_TYPE` ASC) VISIBLE,
  INDEX `fk_mko_has_type_mko1_idx` (`mko_MKO_VAT` ASC) VISIBLE,
  CONSTRAINT `fk_mko_has_type_mko1`
    FOREIGN KEY (`mko_MKO_VAT`)
    REFERENCES `refugeedb`.`mko` (`MKO_VAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mko_has_type_type1`
    FOREIGN KEY (`type_MKO_TYPE`)
    REFERENCES `mydb`.`type` (`MKO_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`hospital_has_doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`hospital_has_doctor` (
  `hospital_HOS_ID` INT NOT NULL,
  `doctor_DOC_ID` INT NOT NULL,
  PRIMARY KEY (`hospital_HOS_ID`, `doctor_DOC_ID`),
  INDEX `fk_hospital_has_doctor_doctor1_idx` (`doctor_DOC_ID` ASC) VISIBLE,
  INDEX `fk_hospital_has_doctor_hospital1_idx` (`hospital_HOS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_has_doctor_hospital1`
    FOREIGN KEY (`hospital_HOS_ID`)
    REFERENCES `refugeedb`.`hospital` (`HOS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_has_doctor_doctor1`
    FOREIGN KEY (`doctor_DOC_ID`)
    REFERENCES `refugeedb`.`doctor` (`DOC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`government_has_responsibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`government_has_responsibility` (
  `government_GOV_ID` INT NOT NULL,
  `responsibility_RESPONSIBILITY_ID` INT NOT NULL,
  PRIMARY KEY (`government_GOV_ID`, `responsibility_RESPONSIBILITY_ID`),
  INDEX `fk_government_has_responsibility_responsibility1_idx` (`responsibility_RESPONSIBILITY_ID` ASC) VISIBLE,
  INDEX `fk_government_has_responsibility_government1_idx` (`government_GOV_ID` ASC) VISIBLE,
  CONSTRAINT `fk_government_has_responsibility_government1`
    FOREIGN KEY (`government_GOV_ID`)
    REFERENCES `refugeedb`.`government` (`GOV_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_government_has_responsibility_responsibility1`
    FOREIGN KEY (`responsibility_RESPONSIBILITY_ID`)
    REFERENCES `mydb`.`responsibility` (`RESPONSIBILITY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`refugee_has_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`refugee_has_family` (
  `refugee_REF_ID` INT NOT NULL,
  `family_FAM_ID` INT NOT NULL,
  PRIMARY KEY (`refugee_REF_ID`, `family_FAM_ID`),
  INDEX `fk_refugee_has_family_family1_idx` (`family_FAM_ID` ASC) VISIBLE,
  INDEX `fk_refugee_has_family_refugee1_idx` (`refugee_REF_ID` ASC) VISIBLE,
  CONSTRAINT `fk_refugee_has_family_refugee1`
    FOREIGN KEY (`refugee_REF_ID`)
    REFERENCES `refugeedb`.`refugee` (`REF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refugee_has_family_family1`
    FOREIGN KEY (`family_FAM_ID`)
    REFERENCES `refugeedb`.`family` (`FAM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


-- -----------------------------------------------------
-- Table `refugeedb`.`refugee_has_allergies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refugeedb`.`refugee_has_allergies` (
  `refugee_REF_ID` INT NOT NULL,
  `allergies_REF_ID` INT NOT NULL,
  PRIMARY KEY (`refugee_REF_ID`, `allergies_REF_ID`),
  INDEX `fk_refugee_has_allergies_allergies1_idx` (`allergies_REF_ID` ASC) VISIBLE,
  INDEX `fk_refugee_has_allergies_refugee1_idx` (`refugee_REF_ID` ASC) VISIBLE,
  CONSTRAINT `fk_refugee_has_allergies_refugee1`
    FOREIGN KEY (`refugee_REF_ID`)
    REFERENCES `refugeedb`.`refugee` (`REF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refugee_has_allergies_allergies1`
    FOREIGN KEY (`allergies_REF_ID`)
    REFERENCES `refugeedb`.`allergies` (`ALL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = greek;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
